# add bits here as needed

my_experiment: "RKN_lib3"

data_dir: "data/libraries/RKN_lib3"
# kraken2_db: "data/databases/meloidogyne_tomato_human_db"
# kraken2_db: "data/databases/meloidogyne_tomato_human_no-mask_db"
kraken2_db: "data/databases/meloidogyne_tomato_human_sweetpotato_no-mask_db"
# kraken2_db: "data/databases/meloidogyne_tomato_db_m1_k31"
# kraken2_db: "data/databases/meloidogyne_mitogenomes_db"
# kraken2_db: "data/databases/bacteria_db"

taxdump: "data/databases/taxdump"
