# add bits here as needed

# name of your experiment:
my_experiment: "my_experiment"  # change as needed

# tab delimited file with a sample name per line (i.e. barcode01)
sample_list: "samples.tsv"  # change as needed

# path to dorectory of input files. See "input_type" (below)
data_dir: "data/libraries/my_library"  # change as needed

#-------------------------------------------------------------------------------
# Input_type:
# options: "guppy" or "fastq"

# "guppy": input files located in a guppy basecaller output directory
# "fastq": input files located in a directory containing fastqs (1 per sample)

input_type: "guppy"

#-------------------------------------------------------------------------------
# Kraken 2 database directory (path to directory):
kraken2_db: "data/databases/RKN_final_db"  # change as needed

# taxdump directory for Recentrifuge:
# contains names.dmp and nodes.dmp
taxdump: "data/databases/taxdump"  # change as needed

#-------------------------------------------------------------------------------

# Nanofilt quality control settings:

qual: 0  # change as needed

len: 1000   # change as needed

head: 50  # change as needed

tail: 50  # change as needed

#-------------------------------------------------------------------------------

# Kraken 2 taxonomic classification settings:

minq: 7  # change as needed

conf: 0.02  # change as needed
