# add bits here as needed

my_experiment: "RKN_lib3"  # change as needed

data_dir: "data/libraries/RKN_lib3"  # change as needed

kraken2_db: "data/databases/meloidogyne_tomato_human_sweetpotato_no-mask_db"  # change as needed

taxdump: "data/databases/taxdump"  # change as needed
