# name of your experiment:
my_experiment: "my_experiment"

# tab delimited file with a sample name per line (i.e. barcode01)
sample_list: "RKN_test_samples.tsv"

# path to dorectory of input files. See "input_type" (below)
data_dir: "data/libraries/RKN_test_library"

#-------------------------------------------------------------------------------
# Input_type:
# options: "guppy" or "fastq"

# "guppy": input files located in a guppy basecaller output directory
# "fastq": input files located in a directory containing fastqs (1 per sample)

input_type: "guppy"

#-------------------------------------------------------------------------------
# Kraken 2 database directory (path to directory):
kraken2_db: "data/databases/RKN_db"

# taxdump directory for Recentrifuge:
# contains names.dmp and nodes.dmp
taxdump: "data/databases/taxdump"

#-------------------------------------------------------------------------------

# Nanofilt quality control settings:

qual: 0

len: 1000

head: 50

tail: 50

#-------------------------------------------------------------------------------

# Kraken 2 taxonomic classification settings:

minq: 7

conf: 0.02
